name: 'Generate meeting slides'
description: 'Create a pdf presentation with PR and issue overview'
branding:
  icon: 'monitor'
  color: 'blue'
inputs:
  config:
    description: 'Configuration yaml snippet (see https://pypi.org/project/mtng/)'
    required: true
  since:
    description: 'Meta-date since when slides should be made'
    required: false
    default: '1 week ago'
runs:
  using: "composite"
  steps:
    - uses: actions/cache@v3
      id: cache-venv
      with:
        path: ./.venv/
        key: ${{ runner.os }}-venv-${{ hashFiles('**/requirements*.txt') }}
        restore-keys: |
          ${{ runner.os }}-venv-
    - run: |
        python -m venv ./.venv
        . ./.venv/bin/activate
        pip install -r requirements.txt
      if: steps.cache-venv.outputs.cache-hit != 'true'
      shell: bash
    - run: |
        . ./.venv/bin/activate
        echo "${{ inputs.config }}" | tee config.yml
        since=$(date --date="${{ inputs.since }}" +'%Y-%m-%d %H:%M:%S')
        mtng generate --token="${{ github.token }}" --since="${since}" config.yml | tee slides.tex
      shell: bash
    - uses: xu-cheng/latex-action@v2
      with:
        root_file: |
          ${{ github.action_path }}/presentation.tex
    - uses: actions/upload-artifact@v3
      with:
        name: presentation.pdf
        path: presentation.pdf
